# coding: utf-8

# flake8: noqa

"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "MetaV2Api",
    "MetaV3Api",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BuildResponse",
    "Checksums",
    "Commit",
    "Download",
    "ErrorResponse",
    "Java",
    "JavaFlags",
    "JavaVersion",
    "Project",
    "ProjectResponse",
    "ProjectsResponse",
    "Support",
    "Version",
    "VersionResponse",
    "VersionsResponse",
]

# import apis into sdk package
from papermc_api_client.api.meta_v2_api import MetaV2Api as MetaV2Api
from papermc_api_client.api.meta_v3_api import MetaV3Api as MetaV3Api

# import ApiClient
from papermc_api_client.api_response import ApiResponse as ApiResponse
from papermc_api_client.api_client import ApiClient as ApiClient
from papermc_api_client.configuration import Configuration as Configuration
from papermc_api_client.exceptions import OpenApiException as OpenApiException
from papermc_api_client.exceptions import ApiTypeError as ApiTypeError
from papermc_api_client.exceptions import ApiValueError as ApiValueError
from papermc_api_client.exceptions import ApiKeyError as ApiKeyError
from papermc_api_client.exceptions import ApiAttributeError as ApiAttributeError
from papermc_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from papermc_api_client.models.build_response import BuildResponse as BuildResponse
from papermc_api_client.models.checksums import Checksums as Checksums
from papermc_api_client.models.commit import Commit as Commit
from papermc_api_client.models.download import Download as Download
from papermc_api_client.models.error_response import ErrorResponse as ErrorResponse
from papermc_api_client.models.java import Java as Java
from papermc_api_client.models.java_flags import JavaFlags as JavaFlags
from papermc_api_client.models.java_version import JavaVersion as JavaVersion
from papermc_api_client.models.project import Project as Project
from papermc_api_client.models.project_response import ProjectResponse as ProjectResponse
from papermc_api_client.models.projects_response import ProjectsResponse as ProjectsResponse
from papermc_api_client.models.support import Support as Support
from papermc_api_client.models.version import Version as Version
from papermc_api_client.models.version_response import VersionResponse as VersionResponse
from papermc_api_client.models.versions_response import VersionsResponse as VersionsResponse

