# coding: utf-8

# flake8: noqa

"""
    PaperMC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from papermc_api_client.api.download_controller_api import DownloadControllerApi
from papermc_api_client.api.project_controller_api import ProjectControllerApi
from papermc_api_client.api.projects_controller_api import ProjectsControllerApi
from papermc_api_client.api.version_build_controller_api import VersionBuildControllerApi
from papermc_api_client.api.version_builds_controller_api import VersionBuildsControllerApi
from papermc_api_client.api.version_controller_api import VersionControllerApi
from papermc_api_client.api.version_family_builds_controller_api import VersionFamilyBuildsControllerApi
from papermc_api_client.api.version_family_controller_api import VersionFamilyControllerApi

# import ApiClient
from papermc_api_client.api_response import ApiResponse
from papermc_api_client.api_client import ApiClient
from papermc_api_client.configuration import Configuration
from papermc_api_client.exceptions import OpenApiException
from papermc_api_client.exceptions import ApiTypeError
from papermc_api_client.exceptions import ApiValueError
from papermc_api_client.exceptions import ApiKeyError
from papermc_api_client.exceptions import ApiAttributeError
from papermc_api_client.exceptions import ApiException

# import models into sdk package
from papermc_api_client.models.build_response import BuildResponse
from papermc_api_client.models.builds_response import BuildsResponse
from papermc_api_client.models.change import Change
from papermc_api_client.models.download import Download
from papermc_api_client.models.project_response import ProjectResponse
from papermc_api_client.models.projects_response import ProjectsResponse
from papermc_api_client.models.version_build import VersionBuild
from papermc_api_client.models.version_family_build import VersionFamilyBuild
from papermc_api_client.models.version_family_builds_response import VersionFamilyBuildsResponse
from papermc_api_client.models.version_family_response import VersionFamilyResponse
from papermc_api_client.models.version_response import VersionResponse
