# coding: utf-8

# flake8: noqa
"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from papermc_api_client.models.build_response import BuildResponse
from papermc_api_client.models.checksums import Checksums
from papermc_api_client.models.commit import Commit
from papermc_api_client.models.download import Download
from papermc_api_client.models.error_response import ErrorResponse
from papermc_api_client.models.java import Java
from papermc_api_client.models.java_flags import JavaFlags
from papermc_api_client.models.java_version import JavaVersion
from papermc_api_client.models.project import Project
from papermc_api_client.models.project_response import ProjectResponse
from papermc_api_client.models.projects_response import ProjectsResponse
from papermc_api_client.models.support import Support
from papermc_api_client.models.version import Version
from papermc_api_client.models.version_response import VersionResponse
from papermc_api_client.models.versions_response import VersionsResponse

