# coding: utf-8

"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from papermc_api_client.api.meta_v3_api import MetaV3Api


class TestMetaV3Api(unittest.TestCase):
    """MetaV3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaV3Api()

    def tearDown(self) -> None:
        pass

    def test_get_build(self) -> None:
        """Test case for get_build

        Get details of a specific build for a version of a project
        """
        pass

    def test_get_builds(self) -> None:
        """Test case for get_builds

        Get a list of builds for a specific version of a project
        """
        pass

    def test_get_latest_build(self) -> None:
        """Test case for get_latest_build

        Get details of the latest build for a version of a project
        """
        pass

    def test_get_project(self) -> None:
        """Test case for get_project

        Get details of a specific project
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        Get a list of all projects
        """
        pass

    def test_get_version(self) -> None:
        """Test case for get_version

        Get details of a specific version for a project
        """
        pass

    def test_get_versions(self) -> None:
        """Test case for get_versions

        Get a list of versions for a specific project
        """
        pass


if __name__ == '__main__':
    unittest.main()
