# coding: utf-8

"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from papermc_api_client.models.version import Version

class TestVersion(unittest.TestCase):
    """Version unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Version:
        """Test Version
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Version`
        """
        model = Version()
        if include_optional:
            return Version(
                id = '',
                java = papermc_api_client.models.java.Java(
                    flags = papermc_api_client.models.java_flags.JavaFlags(
                        recommended = [
                            ''
                            ], ), 
                    version = papermc_api_client.models.java_version.JavaVersion(
                        minimum = 56, ), ),
                support = papermc_api_client.models.support.Support(
                    end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    status = 'SUPPORTED', )
            )
        else:
            return Version(
        )
        """

    def testVersion(self):
        """Test Version"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
