# coding: utf-8

"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from papermc_api_client.models.java import Java

class TestJava(unittest.TestCase):
    """Java unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Java:
        """Test Java
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Java`
        """
        model = Java()
        if include_optional:
            return Java(
                flags = papermc_api_client.models.java_flags.JavaFlags(
                    recommended = [
                        ''
                        ], ),
                version = papermc_api_client.models.java_version.JavaVersion(
                    minimum = 56, )
            )
        else:
            return Java(
        )
        """

    def testJava(self):
        """Test Java"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
