# coding: utf-8

"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from papermc_api_client.models.versions_response import VersionsResponse

class TestVersionsResponse(unittest.TestCase):
    """VersionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionsResponse:
        """Test VersionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionsResponse`
        """
        model = VersionsResponse()
        if include_optional:
            return VersionsResponse(
                versions = [
                    papermc_api_client.models.version_response.VersionResponse(
                        builds = [
                            56
                            ], 
                        version = papermc_api_client.models.version.Version(
                            id = '', 
                            java = papermc_api_client.models.java.Java(
                                flags = papermc_api_client.models.java_flags.JavaFlags(
                                    recommended = [
                                        ''
                                        ], ), ), 
                            support = papermc_api_client.models.support.Support(
                                end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                status = 'SUPPORTED', ), ), )
                    ]
            )
        else:
            return VersionsResponse(
        )
        """

    def testVersionsResponse(self):
        """Test VersionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
