# coding: utf-8

"""
    PaperMC Fill

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from papermc_api_client.api.meta_v2_api import MetaV2Api


class TestMetaV2Api(unittest.TestCase):
    """MetaV2Api unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaV2Api()

    def tearDown(self) -> None:
        pass

    def test_get_family(self) -> None:
        """Test case for get_family

        """
        pass

    def test_get_family_builds(self) -> None:
        """Test case for get_family_builds

        """
        pass

    def test_get_project1(self) -> None:
        """Test case for get_project1

        """
        pass

    def test_get_projects1(self) -> None:
        """Test case for get_projects1

        """
        pass

    def test_get_version1(self) -> None:
        """Test case for get_version1

        """
        pass

    def test_get_version_build(self) -> None:
        """Test case for get_version_build

        """
        pass

    def test_get_version_builds(self) -> None:
        """Test case for get_version_builds

        """
        pass


if __name__ == '__main__':
    unittest.main()
